"""add session lock times to events

Revision ID: 01bd527e8740
Revises: a0fb7ad3f48f
Create Date: 2026-08-07 21:59:38.578812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01bd527e8740'
down_revision: Union[str, Sequence[str], None] = 'a0fb7ad3f48f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('qualifying_start_time', sa.DateTime(), nullable=False))
    op.add_column('events', sa.Column('sprint_start_time', sa.DateTime(), nullable=True))
    op.add_column('events', sa.Column('race_start_time', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'race_start_time')
    op.drop_column('events', 'sprint_start_time')
    op.drop_column('events', 'qualifying_start_time')
    # ### end Alembic commands ###
