"""add next_round_number to seasons

Revision ID: 6dc8c0d6ffd5
Revises: 01bd527e8740
Create Date: 2026-08-10 16:49:03.828211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dc8c0d6ffd5'
down_revision: Union[str, Sequence[str], None] = '01bd527e8740'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seasons', sa.Column('next_round_number', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seasons', 'next_round_number')
    # ### end Alembic commands ###
